---
- hosts: localhost
  tasks:
    - name: Run script
      copy:
        src: url.sh
        dest: url.sh
      become: yes

    - name: cronjobs
      cron:
        minute: "*/5"
        job: "/bin/bash url.sh"
      become: yes
